name: Release Build

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 3.5.1)'
        required: false
        default: '3.5.1'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi,nsis
          - os: macos-latest
            target: x86_64-apple-darwin
            bundles: dmg
          - os: macos-latest
            target: aarch64-apple-darwin
            bundles: dmg
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bundles: deb,appimage

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev librsvg2-dev
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build Tauri app
        run: pnpm tauri build --target ${{ matrix.target }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/*/release/bundle/*/*
          
      # 如果是release触发，自动上传到release
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/*/release/bundle/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
